name = "TDD"
uuid = "61f67d44-e29f-44b5-a4b4-271cf286d797"
authors = ["Xubo Leng <hsupo.leng@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
